// Code generated by bpf2go; DO NOT EDIT.
//go:build (mips || mips64 || ppc64 || s390x) && linux

package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// loadCollector returns the embedded CollectionSpec for collector.
func loadCollector() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_CollectorBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load collector: %w", err)
	}

	return spec, err
}

// loadCollectorObjects loads collector and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*collectorObjects
//	*collectorPrograms
//	*collectorMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadCollectorObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadCollector()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// collectorSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type collectorSpecs struct {
	collectorProgramSpecs
	collectorMapSpecs
	collectorVariableSpecs
}

// collectorProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type collectorProgramSpecs struct {
	WriteOps *ebpf.ProgramSpec `ebpf:"write_ops"`
}

// collectorMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type collectorMapSpecs struct {
	PktCount *ebpf.MapSpec `ebpf:"pkt_count"`
}

// collectorVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type collectorVariableSpecs struct {
}

// collectorObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadCollectorObjects or ebpf.CollectionSpec.LoadAndAssign.
type collectorObjects struct {
	collectorPrograms
	collectorMaps
	collectorVariables
}

func (o *collectorObjects) Close() error {
	return _CollectorClose(
		&o.collectorPrograms,
		&o.collectorMaps,
	)
}

// collectorMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadCollectorObjects or ebpf.CollectionSpec.LoadAndAssign.
type collectorMaps struct {
	PktCount *ebpf.Map `ebpf:"pkt_count"`
}

func (m *collectorMaps) Close() error {
	return _CollectorClose(
		m.PktCount,
	)
}

// collectorVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadCollectorObjects or ebpf.CollectionSpec.LoadAndAssign.
type collectorVariables struct {
}

// collectorPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadCollectorObjects or ebpf.CollectionSpec.LoadAndAssign.
type collectorPrograms struct {
	WriteOps *ebpf.Program `ebpf:"write_ops"`
}

func (p *collectorPrograms) Close() error {
	return _CollectorClose(
		p.WriteOps,
	)
}

func _CollectorClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed collector_bpfeb.o
var _CollectorBytes []byte
